name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_reason:
        description: 'Reason for deployment'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      NODE_VERSION: '18'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: csmcl.space
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "Starting deployment at $(date)"
            echo "Deployment reason: ${{ github.event.inputs.deploy_reason || 'Automated deployment from push to main' }}"
            
            # Navigate to project directory
            cd /var/www/csmcl.space
            
            # Pull latest changes
            git pull origin main
            
            # Frontend deployment
            echo "Deploying frontend..."
            cd frontend
            npm ci
            npm run build
            
            # Backend deployment
            echo "Deploying backend..."
            cd ../backend
            npm ci
            
            # Verify directory structure and permissions
            echo "Setting up directory structure..."
            sudo mkdir -p /var/www/csmcl.space/backend
            sudo chown -R www-data:www-data /var/www/csmcl.space
            
            # Copy backend files
            echo "Copying backend files..."
            sudo cp -r * /var/www/csmcl.space/backend/
            
            # Setup systemd service
            echo "Setting up systemd service..."
            echo "1. Copying service file..."
            sudo cp deployment/systemd/csmcl-space.service /etc/systemd/system/
            sudo chown root:root /etc/systemd/system/csmcl-space.service
            sudo chmod 644 /etc/systemd/system/csmcl-space.service
            
            echo "2. Reloading systemd..."
            sudo systemctl daemon-reload
            
            echo "3. Enabling service..."
            sudo systemctl enable csmcl-space
            
            echo "4. Starting service..."
            sudo systemctl start csmcl-space || {
              echo "Service failed to start. Checking status..."
              sudo systemctl status csmcl-space --no-pager || true
              echo "Checking logs..."
              sudo journalctl -u csmcl-space --no-pager -n 50 || true
            }
            
            echo "Deployment completed successfully at $(date)"
