name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      NODE_VERSION: '18'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: csmcl.space
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "Starting deployment at $(date)"
            
            echo "Updating repository..."
            cd /var/www/csmcl.space
            git pull origin main
            
            echo "Building frontend..."
            cd frontend
            npm ci
            npm run build
            
            echo "Updating backend..."
            cd ../backend
            npm ci
            
            echo "Restarting services..."
            sudo systemctl restart csmcl-space
            
            echo "Checking service status..."
            sudo systemctl status csmcl-space --no-pager
            
            echo "Deployment completed at $(date)"
