name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      NODE_VERSION: '18'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H csmcl.space >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          echo "Starting deployment at $(date)"
          
          # Test SSH connection
          if ! ssh -i ~/.ssh/deploy_key root@csmcl.space whoami; then
            echo "SSH connection failed"
            exit 1
          fi
          
          # Deploy using SSH
          ssh -i ~/.ssh/deploy_key root@csmcl.space '
            set -e
            cd /var/www/csmcl.space || exit 1
            
            echo "Pulling latest changes..."
            git pull origin main
            
            echo "Building frontend..."
            cd frontend
            npm ci
            npm run build
            
            echo "Updating backend..."
            cd ../backend
            npm ci
            
            echo "Restarting services..."
            sudo systemctl restart csmcl-space
            
            echo "Checking service status..."
            sudo systemctl status csmcl-space --no-pager
          '
