name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H csmcl.space >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@csmcl.space 'echo "SSH connection successful"'

      - name: Deploy
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key root@csmcl.space '
            cd /var/www/csmcl.space
            git pull origin main
            cd frontend && npm ci && npm run build
            cd ../backend && npm ci
            sudo systemctl restart csmcl-space
          '
